# Generated by Django 5.0.6 on 2024-06-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='slug',
            field=models.CharField(default='', max_length=10),
        ),
    ]
