# Generated by Django 5.0.6 on 2024-05-21 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchinfo',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 11, 51, 15, 178777)),
        ),
    ]