# Generated by Django 5.0.6 on 2024-05-21 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_user', '0002_alter_matchinfo_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestat',
            name='game_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 11, 54, 49, 898279)),
        ),
    ]
