# 기본 이미지로 Nginx를 사용합니다.
FROM nginx:alpine

RUN  apk update && apk upgrade
RUN  apk add --update bash && \
     apk add nginx \
     openssl 

EXPOSE 80

WORKDIR /

RUN   mkdir -p /etc/ssl
RUN   chmod +x /etc/ssl

# 작업 디렉토리를 /etc/nginx/ssl로 설정합니다.
WORKDIR /etc/ssl

# 기본 Nginx 설정 파일을 교체합니다.
COPY --chmod=755 ./ft_back/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --chmod=755 ./ft_back/nginx/init.sh /init.sh

# Start dumb-init for PID 1
ENTRYPOINT ["/bin/sh", "/init.sh"]